# FILE: helm/helm-chart/templates/secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: shviki-aws-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1 # This comes from your gitops/values.yaml global key
      auth:
        jwt:
          serviceAccountRef:
            name: shviki-fitness-sa # The SA created by your Terraform