apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: shviki-fitness
type: Opaque
stringData:
  SECRET_KEY: super-secret-key
  EXERCISE_API_KEY: a7e283e943msh9ef1e13e34a30a1p106ce1jsn207b35aa2876
  EXERCISE_API_HOST: exercisedb-api1.p.rapidapi.com
