apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: shviki-fitness
type: Opaque
stringData:
  MYSQL_DATABASE: shviki_db
  MYSQL_USER: shviki_user
  MYSQL_PASSWORD: shviki_pass
  MYSQL_ROOT_PASSWORD: root_password
